apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tuyen-real-world-pvc-data
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
