apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: shared-sealedsecret-database
  
  
# oc create secret generic shared-sealedsecret-database \
# --from-literal=MYSQL_ROOT_PASSWORD=root \
# --dry-run -o yaml > shared-secret-database-temp.yaml

# cat shared-secret-database-temp.yaml | /snap/sealed-secrets-kubeseal-nsg/1/bin/kubeseal \
# --controller-namespace kube-system -o yaml --scope strict > shared-sealedsecret-database.yaml